# Generated by Django 5.1.6 on 2025-03-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
