# Generated by Django 5.1.7 on 2025-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='WorkPlace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
