# Generated by Django 5.1.7 on 2025-03-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0002_alter_workplace_workplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='work_place',
        ),
    ]
