# Generated by Django 5.1.3 on 2024-12-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0002_remove_offer_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_image',
            field=models.ImageField(default=1, upload_to='offer'),
            preserve_default=False,
        ),
    ]
