# Generated by Django 5.1.7 on 2025-03-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0003_remove_customerreview_work_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='phone_number',
            new_name='customer_id',
        ),
    ]
