# Generated by Django 5.1.6 on 2025-03-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0003_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
