# Generated by Django 5.1.7 on 2025-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0004_rename_phone_number_customerreview_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
