# Generated by Django 5.1.3 on 2024-12-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0005_our_works_work_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_works',
            old_name='Work_title',
            new_name='Worktitle',
        ),
        migrations.RenameField(
            model_name='our_works',
            old_name='profile_image',
            new_name='profileimage',
        ),
        migrations.DeleteModel(
            name='Work_images',
        ),
    ]
