# Generated by Django 5.1.3 on 2024-12-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0006_rename_work_title_our_works_worktitle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='offer',
        ),
        migrations.DeleteModel(
            name='Our_Works',
        ),
    ]
