# Generated by Django 5.1.3 on 2024-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('work_category', models.CharField(max_length=125)),
                ('thumbnail_img', models.ImageField(upload_to='works')),
                ('images', models.ImageField(upload_to='works')),
                ('description', models.TextField()),
            ],
        ),
    ]
