# Generated by Django 5.1.3 on 2024-12-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0009_our_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('services', models.CharField(max_length=225)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='our_works',
            name='images',
        ),
        migrations.CreateModel(
            name='Addiotional_work_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genrapp.our_works')),
            ],
        ),
    ]
