# Generated by Django 5.0.4 on 2024-12-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0010_enquiry_remove_our_works_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='gallery_image',
        ),
    ]
