# Generated by Django 5.0.4 on 2024-12-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0011_rename_image_gallery_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
