# Generated by Django 5.0.4 on 2024-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0012_alter_gallery_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, default='no file choosen', null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='banner_title',
            field=models.CharField(blank=True, default='no file choosen', max_length=125),
        ),
    ]
