# Generated by Django 5.0.4 on 2024-12-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0013_alter_gallery_gallery_image_alter_offer_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='banner_title',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
