# Generated by Django 5.0.4 on 2024-12-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0014_alter_gallery_gallery_image_alter_offer_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
