# Generated by Django 5.0.4 on 2025-01-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0015_gallery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=225)),
                ('job_description', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('work_time', models.TextField()),
            ],
        ),
    ]
