# Generated by Django 5.1.3 on 2025-01-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0016_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='news')),
            ],
        ),
    ]
