# Generated by Django 5.1.6 on 2025-02-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0018_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='banner_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='banner_title',
            field=models.CharField(default='Our Offers', max_length=125),
        ),
    ]
